# -*- coding: utf-8 -*-
"""Hall.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BfGnJOY3alIxPQbxou3ccs1-Rw9W_xxO
"""

#class defination for Hall
import pickle as pk
class Hall:
  #attributes of the class

  def __init__(self, name, phone_number, address, booking_date, cost, owner):
    self.name = name
    self.phone_number = phone_number
    self.address = address
    self.booking_date = booking_date
    self.cost = cost
    self.owner = owner

  # defination of __eq__ fu8nction for comparison operation
  def __eq__(self, obj):
    if((self.name == obj.name) and (self.phone_number == obj.phone_number) and (self.booking_date == obj.booking_date)):
      return 1
    else:
      return 0
  # display function for output of the details
  def display(self):
    print("\nDisplay the Booked Hall details\n")
    print("Hall Name :" + self.name)
    print("\nPhone No :" + str(self.phone_number))
    print("\nAddress :"+ self.address)
    print("\nCost :"+ str(self.cost))
    print("\nOwner name :" + self.owner)

# reading number of enteries of booking
n = int(input("Enter the number of Entries \n"))

# reading details of each booking and passing it to save into a file
for i in range(n):
  print("Enter details of Hall " + str(i+1))
  name = input("\nEnter Hall name\n")
  phone_number = int(input("\nEnter Phone\n"))
  address = input("\nEnter Address\n")
  booking_date = input("\nEnter Date of booking\n")
  cost = int(input("\nEnter cost\n"))
  owner = input("\nEnter owner name\n")

  obj = Hall(name, phone_number, address, booking_date, cost, owner)
  with open('Data.pkl', 'wb') as f:
    pk.dump(obj,f)

# getting details for new booking
print("\nEnter the Hall details for booking\n")
name = input("\nEnter Hall name\n")
phone_number = input("\nEnter Phone\n")
address = input("\nEnter Address\n")
booking_date = input("\nEnter Date of booking\n")
cost = input("\nEnter cost\n")
owner = input("\nEnter owner name\n")

obj = Hall(name, phone_number, address, booking_date, cost, owner)


# reading the file to check if the booking is already done or not 
data = []
with open('Data.pkl', 'rb') as f:
  while True:
        try:
            data.append(pk.load(f))
        except EOFError:
            break

flag  = 0
for d in data:
  status = d.__eq__(obj)
  if(status == 1):
    print("\nAlready Registered\n")
    obj.display()
    flag = 1
    break


if(flag == 0):
  for d in data:
    d.display()
    print('\n')
  obj.display()

